# Generated by Django 5.1.1 on 2024-09-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='clothes/')),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('clima', models.CharField(blank=True, max_length=50, null=True)),
                ('parte_cuerpo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], default='A', max_length=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('sport', 'Sport')], max_length=50)),
                ('clima', models.CharField(choices=[('caluroso', 'Caluroso'), ('frío', 'Frío'), ('templado', 'Templado')], max_length=50)),
                ('fecha_programacion', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], default='A', max_length=1)),
                ('Prendas', models.ManyToManyField(related_name='combinaciones', to='api.prenda')),
            ],
        ),
    ]
